"""cloudfleet replica tables

Revision ID: 1b51b7ed68c3
Revises: p6q7r8s90016
Create Date: 2026-07-03 19:06:53.892021

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b51b7ed68c3'
down_revision: str | None = 'p6q7r8s90016'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloudfleet_maintenance_schedules',
    sa.Column('consecutive', sa.BigInteger(), nullable=True),
    sa.Column('vehicle_code', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('task_name', sa.String(), nullable=True),
    sa.Column('routine_name', sa.String(), nullable=True),
    sa.Column('schedule_type', sa.String(), nullable=True),
    sa.Column('schedule_source', sa.String(), nullable=True),
    sa.Column('date_to_execute', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_to_execute_days_diff', sa.Float(), nullable=True),
    sa.Column('wo_number', sa.BigInteger(), nullable=True),
    sa.Column('wo_execution_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consecutive', 'date_to_execute', name='uq_cf_schedule_consecutive_date')
    )
    op.create_index(op.f('ix_cloudfleet_maintenance_schedules_date_to_execute'), 'cloudfleet_maintenance_schedules', ['date_to_execute'], unique=False)
    op.create_index(op.f('ix_cloudfleet_maintenance_schedules_vehicle_code'), 'cloudfleet_maintenance_schedules', ['vehicle_code'], unique=False)
    op.create_table('cloudfleet_vehicles',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('brand_name', sa.String(), nullable=True),
    sa.Column('line_name', sa.String(), nullable=True),
    sa.Column('type_name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('cost_center', sa.String(), nullable=True),
    sa.Column('primary_group', sa.String(), nullable=True),
    sa.Column('group1', sa.String(), nullable=True),
    sa.Column('odometer', sa.Float(), nullable=True),
    sa.Column('hourmeter', sa.Float(), nullable=True),
    sa.Column('is_in_master', sa.Boolean(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloudfleet_vehicles_code'), 'cloudfleet_vehicles', ['code'], unique=True)
    op.create_table('cloudfleet_work_orders',
    sa.Column('number', sa.BigInteger(), nullable=False),
    sa.Column('vehicle_code', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('detected_issue', sa.Text(), nullable=True),
    sa.Column('affects_vehicle_availability', sa.Boolean(), nullable=False),
    sa.Column('warranty', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('workshop_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('technical_completion_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_completion_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_finish_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cf_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cf_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cost_center', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('total_cost', sa.Numeric(), nullable=True),
    sa.Column('total_cost_labors', sa.Numeric(), nullable=True),
    sa.Column('total_cost_parts', sa.Numeric(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index('ix_cf_wo_start_date', 'cloudfleet_work_orders', ['start_date'], unique=False)
    op.create_index('ix_cf_wo_technical_completion_date', 'cloudfleet_work_orders', ['technical_completion_date'], unique=False)
    op.create_index(op.f('ix_cloudfleet_work_orders_status'), 'cloudfleet_work_orders', ['status'], unique=False)
    op.create_index(op.f('ix_cloudfleet_work_orders_vehicle_code'), 'cloudfleet_work_orders', ['vehicle_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cloudfleet_work_orders_vehicle_code'), table_name='cloudfleet_work_orders')
    op.drop_index(op.f('ix_cloudfleet_work_orders_status'), table_name='cloudfleet_work_orders')
    op.drop_index('ix_cf_wo_technical_completion_date', table_name='cloudfleet_work_orders')
    op.drop_index('ix_cf_wo_start_date', table_name='cloudfleet_work_orders')
    op.drop_table('cloudfleet_work_orders')
    op.drop_index(op.f('ix_cloudfleet_vehicles_code'), table_name='cloudfleet_vehicles')
    op.drop_table('cloudfleet_vehicles')
    op.drop_index(op.f('ix_cloudfleet_maintenance_schedules_vehicle_code'), table_name='cloudfleet_maintenance_schedules')
    op.drop_index(op.f('ix_cloudfleet_maintenance_schedules_date_to_execute'), table_name='cloudfleet_maintenance_schedules')
    op.drop_table('cloudfleet_maintenance_schedules')
    # ### end Alembic commands ###
