"""drop cloudfleet schedule unique constraint

Revision ID: 364f6337bf44
Revises: 1b51b7ed68c3
Create Date: 2026-07-03 20:48:59.468868

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '364f6337bf44'
down_revision: str | None = '1b51b7ed68c3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_cf_schedule_consecutive_date'), 'cloudfleet_maintenance_schedules', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_cf_schedule_consecutive_date'), 'cloudfleet_maintenance_schedules', ['consecutive', 'date_to_execute'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
